apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notes-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notes-app-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20  # Lower CPU threshold to trigger scaling
